config/routes.rb
Rails.application.routes.draw do
  resources :pre_student_garbages
  resources :academic_years
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :office_expenses
  resources :fee_structures
  resources :student_fees
  resources :class_infos
  resources :students
  root 'class_infos#index'

  get 'get_allocated_fee', to: 'students#update_allocated_fee'
  get 'update_discount', to: 'students#update_discount'
  get 'print_receipt', to: 'students#print_receipt'

  get 'student_dashboard', to: 'students#dashboard'
  get 'search_student_by_name', to: 'students#search_student_name'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/class_info.rb
class ClassInfo < ApplicationRecord
end

app/controllers/class_infos_controller.rb
class ClassInfosController < ApplicationController
  before_action :set_class_info, only: [:show, :edit, :update, :destroy]

  # GET /class_infos
  # GET /class_infos.json
  def index
    @class_infos = ClassInfo.all
  end

  # GET /class_infos/1
  # GET /class_infos/1.json
  def show
  end

  # GET /class_infos/new
  def new
    @class_info = ClassInfo.new
  end

  # GET /class_infos/1/edit
  def edit
  end

  # POST /class_infos
  # POST /class_infos.json
  def create
    @class_info = ClassInfo.new(class_info_params)

    respond_to do |format|
      if @class_info.save
        format.html { redirect_to @class_info, notice: 'Class info was successfully created.' }
        format.json { render :show, status: :created, location: @class_info }
      else
        format.html { render :new }
        format.json { render json: @class_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /class_infos/1
  # PATCH/PUT /class_infos/1.json
  def update
    respond_to do |format|
      if @class_info.update(class_info_params)
        format.html { redirect_to @class_info, notice: 'Class info was successfully updated.' }
        format.json { render :show, status: :ok, location: @class_info }
      else
        format.html { render :edit }
        format.json { render json: @class_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /class_infos/1
  # DELETE /class_infos/1.json
  def destroy
    @class_info.destroy
    respond_to do |format|
      format.html { redirect_to class_infos_url, notice: 'Class info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_class_info
      @class_info = ClassInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def class_info_params
      params.require(:class_info).permit(:class_name, :address, :contact_no, :available_classes, :subjects)
    end
end

app/helpers/class_infos_helper.rb
module ClassInfosHelper
end

app/views/class_infos/_form.html.erb
<%= form_for(class_info) do |f| %>
  <% if class_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(class_info.errors.count, "error") %> prohibited this class_info from being saved:</h2>

      <ul>
      <% class_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :class_name %>
    <%= f.text_field :class_name %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :contact_no %>
    <%= f.text_field :contact_no %>
  </div>

  <div class="field">
    <%= f.label :available_classes %>
    <%= f.text_field :available_classes %>
  </div>

  <div class="field">
    <%= f.label :subjects %>
    <%= f.text_field :subjects %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/class_infos/edit.html.erb
<h1>Editing Class Info</h1>

<%= render 'form', class_info: @class_info %>

<%= link_to 'Show', @class_info %> |
<%= link_to 'Back', class_infos_path %>

app/views/class_infos/index.html.erb
<div class="mdl-grid">
  <div class="mdl-layout-spacer"></div>
  <h3>Welcome to</h3>
  <div class="mdl-layout-spacer"></div>
</div>
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--3-col">
    <div class="mdl-grid">
    <div class="mdl-layout-spacer"></div>
      <%= image_tag 'logo-krisha.png', class: 'responsive', width: 239, height: 200 %>
    <div class="mdl-layout-spacer"></div>
    </div>
  </div>
  <div class="mdl-cell mdl-cell--6-col mdl-typography--text-center">
    <h1>KRISHA FOUNDATION'S</h1>
    <h2><%= ClassInfo.first.class_name.upcase %></h2>
    <strong><em><%= ClassInfo.first.address %></em></strong><br/>
    <strong><em>Contact No: <%= ClassInfo.first.contact_no %></strong></em>
  </div>
  <div class="mdl-cell mdl-cell--3-col">
    <div class="mdl-grid">
    <div class="mdl-layout-spacer"></div>
      <%= image_tag 'logo-dnyanjyoti.jpg', class: 'responsive', width: 239, height: 200 %>
    <div class="mdl-layout-spacer"></div>
    </div>
  </div>
</div>
<br/>
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--3-col mdl-typography--text-center">
    <%= link_to 'Students', student_dashboard_path, class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent' %>
  </div>
  <div class="mdl-cell mdl-cell--3-col mdl-typography--text-center">
    <%= link_to 'Office Expenses', office_expenses_path, class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent' %>
  </div>
  <div class="mdl-cell mdl-cell--3-col mdl-typography--text-center">
    <%= link_to 'Fee Collection', student_fees_path, class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent' %>
  </div>
  <div class="mdl-cell mdl-cell--3-col mdl-typography--text-center">
    <%= link_to 'Fee Structures', fee_structures_path, class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent' %>
  </div>
</div>

app/views/class_infos/new.html.erb
<h1>New Class Info</h1>

<%= render 'form', class_info: @class_info %>

<%= link_to 'Back', class_infos_path %>

app/views/class_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Class name:</strong>
  <%= @class_info.class_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @class_info.address %>
</p>

<p>
  <strong>Contact no:</strong>
  <%= @class_info.contact_no %>
</p>

<p>
  <strong>Available classes:</strong>
  <%= @class_info.available_classes %>
</p>

<p>
  <strong>Subjects:</strong>
  <%= @class_info.subjects %>
</p>

<%= link_to 'Edit', edit_class_info_path(@class_info) %> |
<%= link_to 'Back', class_infos_path %>