config/routes.rb
Rails.application.routes.draw do
  resources :pre_student_garbages
  resources :academic_years
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :office_expenses
  resources :fee_structures
  resources :student_fees
  resources :class_infos
  resources :students
  root 'class_infos#index'

  get 'get_allocated_fee', to: 'students#update_allocated_fee'
  get 'update_discount', to: 'students#update_discount'
  get 'print_receipt', to: 'students#print_receipt'

  get 'student_dashboard', to: 'students#dashboard'
  get 'search_student_by_name', to: 'students#search_student_name'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :student_fees
  belongs_to :academic_year
  has_many :pre_student_garbages

  mount_uploader :profile_photo, StudentProfileUploader
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy, :update_discount]

  # GET /students
  # GET /students.json
  def index
    if !params[:query].nil? && !params[:standard].nil? && !params[:section].nil?
      @students = Student.where("lower(first_name) LIKE lower(?) AND student_class = ? AND division = ?", "%#{params[:query]}%",
                                "#{params[:standard]}", "#{params[:section]}").order(:created_at => "DESC")
    elsif !params[:standard].nil? && !params[:section].nil?
      @students = Student.where("student_class = ? AND division = ?", "#{params[:standard]}",
                                "#{params[:section]}").order(:created_at => "DESC")
    end

    respond_to do |format|
      format.html
      format.xls
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @pre_student_garbage = PreStudentGarbage.new
  end

  # GET /students/new
  def new
    @student = Student.new
    @fee_structure = FeeStructure.all
  end

  # GET /students/1/edit
  def edit
    @fee_structure = FeeStructure.all
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end



  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.student_fees.each do |fee|
      fee.destroy
    end
    student_class = @student.student_class
    student_section = @student.division
    @student.destroy
    
    respond_to do |format|

      format.html { redirect_to controller: 'students', action: 'index',
                                standard: student_class, section: student_section,
                                notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # custom methods
  def update_allocated_fee

    s_class = params[:s_class]
    s_section = params[:s_section]

    @allocated_fee = FeeStructure.where(:student_class => s_class,
                                       :section => s_section).limit(1).first

    respond_to do |format|
      if !@allocated_fee.blank?
        format.js {}
      else
        format.js {}
      end
    end
  end

  def update_discount
    respond_to do |format|
      if params[:discount].blank?
        format.js {}
      else
        @student.update(:discount => params[:discount])
        format.js {}
      end
    end
  end

  def print_receipt
    @payment = StudentFee.find(params[:id])
  end

  def dashboard
    @fee_structures = FeeStructure.all
  end

  def search_student_name
    @students = Student.where("lower(first_name) LIKE lower(?)", "%#{params[:name]}%") unless params[:name].blank?
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:first_name, :last_name,
                                      :father_name, :father_occupation,
                                      :mother_name, :address, :mobile_no,
                                      :date_of_birth, :college_name, :student_class,
                                      :admission_date, :division, :allocated_fee,
                                      :total_paid, :no_of_installments, :discount,
                                      :alternate_mobile, :academic_year_id, :profile_photo)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
  def previous_balance(student)
    pre_bal = 0.0

    student.pre_student_garbages.each do |pre|
      pre_bal += pre.balance_fee
    end

    pre_bal
  end
end

app/views/students/edit.html.erb
<div class="mdl-grid">
  <div class="mdl-layout-spacer"></div>
  <%= render 'form', student: @student %>
  <div class="mdl-layout-spacer"></div>
</div>

app/views/students/index.html.erb
<script type="text/javascript" charset="utf-8">
  $(document).ready(function () {
     $('#page_name').replaceWith("<span id='page_name'> - Students</span>")
  });
</script>
<%= link_to "<i class='material-icons'>keyboard_arrow_left</i> Back".html_safe, student_dashboard_path, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--accent' %>
<div class="mdl-grid">
  <div class="mdl-layout-spacer"></div>
  <div class="" style="overflow: auto">
    <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp" id="myTable_students">
      <thead>

      <tr>
        <form action="<%= students_path %>">
          <th colspan="4">
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
              <input class="mdl-textfield__input" type="text" id="filter_by_query" name="query" value="<%= params[:query] %>">
              <label class="mdl-textfield__label" for="filter_by_query">Search</label>
            </div>
            <input type="hidden" name="standard" value="<%= params[:standard] %>">
            <input type="hidden" name="section" value="<%= params[:section] %>">
          </th>
          <th>
            <button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-button--accent">Search</button>
          </th>
        </form>
        <th colspan="2">
          <%= link_to 'New Student', {controller: 'students', action: 'new',
                                      standard: params[:standard], section: params[:section] },
                      class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
        </th>
        <th colspan="2">
          <%= link_to "Export to Excel", students_path(format: "xls", standard: params[:standard], section: params[:section]), class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
        </th>
      </tr>
      <tr>
        <th class="mdl-data-table__cell--non-numeric">Profile</th>
        <th class="mdl-data-table__cell--non-numeric">Name</th>
        <th class="mdl-data-table__cell--non-numeric">Standard</th>
        <th class="mdl-data-table__cell--non-numeric">Section</th>
        <th class="mdl-data-table__cell--non-numeric">College</th>
        <th class="mdl-data-table__cell--non-numeric">Mobile No.</th>
        <th class="mdl-data-table__cell--non-numeric">Balance Fee</th>
        <th class="mdl-data-table__cell--non-numeric">View</th>
        <th class="mdl-data-table__cell--non-numeric">Edit</th>
        <th class="mdl-data-table__cell--non-numeric">Delete</th>
        <th class="mdl-data-table__cell--non-numeric">Fee Collection</th>
      </tr>
      </thead>

      <tbody style=" height: 50rem;">
      <% @students.each do |student| %>
          <tr>
            <td class="mdl-data-table__cell--non-numeric"><%= image_tag student.profile_photo.blank? ? 'user.png' : student.profile_photo, :width => 50, :height => 50, class: 'img-circle' %></td>
            <td class="mdl-data-table__cell--non-numeric"><%= student.first_name %></td>
            <td class="mdl-data-table__cell--non-numeric"><%= student.student_class %></td>
            <td class="mdl-data-table__cell--non-numeric"><%= student.division %></td>
            <td class="mdl-data-table__cell--non-numeric"><%= student.college_name %></td>
            <td class="mdl-data-table__cell--non-numeric"><%= student.mobile_no %></td>
            <td class="mdl-data-table__cell--non-numeric">&#8377; <%= number_to_indian_currency((previous_balance(student) + student.allocated_fee.to_f - student.discount.to_f) - student.total_paid.to_f) %></td>
            <td class="mdl-data-table__cell--non-numeric">
              <%= link_to student, class: 'mdl-button mdl-js-button mdl-button--icon' do %>
                  <i class="material-icons" id='tt_show_<%= student.id %>'>pageview</i>
              <% end %>
            </td>
            <td class="mdl-data-table__cell--non-numeric">
              <%= link_to "<i class='material-icons' id='tt_edit_#{student.id}' >mode_edit</i>".html_safe,
                           {controller: 'students', action: 'edit', standard: params[:standard],
                            section: params[:section], id: student},
                           {class: 'mdl-button mdl-js-button mdl-button--icon'} %>
            </td>
            <td class="mdl-data-table__cell--non-numeric">
              <%= link_to student, method: :delete, data: { confirm: 'Are you sure?' },
                          class: 'mdl-button mdl-js-button mdl-button--icon' do %>
                  <i class="material-icons" id='tt_delete_<%= student.id %>'>delete</i>
              <% end %>
            </td>
            <td class="mdl-data-table__cell--non-numeric">
              <%= link_to 'Pay Fee',  {controller: 'student_fees', action: 'new', student_id: student.id}, class: 'mdl-button mdl-js-button mdl-button--accent' %>
            </td>
          </tr>

          <div class="mdl-tooltip" data-mdl-for="tt_show_<%= student.id %>">
            <strong>View Student</strong>
          </div>
          <div class="mdl-tooltip" data-mdl-for="tt_edit_<%= student.id %>">
            <strong>Edit Student</strong>
          </div>
          <div class="mdl-tooltip" data-mdl-for="tt_delete_<%= student.id %>">
            <strong>Delete Student</strong>
          </div>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="mdl-layout-spacer"></div>
</div>

app/views/students/new.html.erb
<div class="mdl-grid">
  <div class="mdl-layout-spacer"></div>
  <%= render 'form', student: @student %>
  <div class="mdl-layout-spacer"></div>
</div>
<div class="mdl-grid"></div>

app/views/students/print_receipt.html.erb
<%= link_to "<i class='material-icons'>keyboard_arrow_left</i> Back".html_safe, student_path(@payment.student), class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--accent avoid-in-print' %>
<%= link_to "Print", '#', class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored avoid-in-print', onclick: 'window.print();' %>
<div class="mdl-grid">
  <div class="mdl-layout-spacer"></div>
    <div >
    <%= image_tag 'logo-dnyanjyoti.jpg', class: 'responsive', width: 100, height: 100 %>
    </div>
  <div class="mdl-layout-spacer"></div>
    <div class="mdl-typography--text-center" >
      <h5>KRISHA FOUNDATION'S</h5>
      <em>Reg. No.: MAHARASHTRA/7408/JALGAON F/5984(JALGAON)</em>
      <h5 style="color: red"><%= ClassInfo.first.class_name.upcase %></h5>
      <em><%= ClassInfo.first.address %></em><br/>
      <em>Contact No: <%= ClassInfo.first.contact_no %></em>
    </div>
  <div class="mdl-layout-spacer"></div>
    <div  >
      <%= image_tag 'logo-krisha.png', class: 'responsive', width: 100, height: 100 %>
    </div>
  <div class="mdl-layout-spacer"></div>
</div>
<hr/>
<div class="mdl-grid">
  <span style="float: right">Receipt No.: <%= @payment.id %></span>
  <div class="mdl-layout-spacer"></div>
  <span style="float: right">Date: <%= @payment.payment_date %></span>
</div>
<div class="mdl-grid">
  <div class="mdl-layout-spacer"></div>
  <h5>Fee Receipt </h5>
  <div class="mdl-layout-spacer"></div>
</div>
<div class="mdl-grid">
  <div class="mdl-layout-spacer"></div>
  <div class="mdl-cell mdl-cell--6-col">
    <h6>
      <table class="table table-bordered">
        <tbody>
          <tr>
            <td>Received With Thanks from:</td>
            <th><%= @payment.student.first_name.upcase %></th>
          </tr>
          <tr>
            <td>The Sum of Rupees:</td>
            <th>&#8377; <%= @payment.amount.to_f %></th>
          </tr>
          <tr>
            <td>Payment Mode: </td>
            <th><%= @payment.payment_method %></th>
          </tr>
          <tr>
            <td>Payment Description: </td>
            <th><%= @payment.payment_desc %></th>
          </tr>
          <tr>
            <td>Installment no: </td>
            <th><%= @payment.installment_no %></th>
          </tr>
          <tr>
            <td>Paid By: </td>
            <th><%= @payment.paid_by %></th>
          </tr>
        </tbody>
      </table>
    </h6>
  </div>
  <div class="mdl-layout-spacer"></div>
</div>
<div class="mdl-grid">
  <div class="mdl-layout-spacer"></div>
  <h5><strong>Total: &#8377; <%= @payment.student.allocated_fee.to_f.round(2) - @payment.student.discount.to_f.round(2) %> /-</strong></h5>
  <div class="mdl-layout-spacer"></div>
  <h5><strong>Paid: &#8377; <%= @payment.student.total_paid %> /-</strong></h5>
  <div class="mdl-layout-spacer"></div>
  <h5><strong>Balance: &#8377; <%= (@payment.student.allocated_fee.to_f.round(2) - @payment.student.discount.to_f.round(2)) - @payment.student.total_paid.to_f.round(2) %> /-</strong></h5>
  <div class="mdl-layout-spacer"></div>
</div>
<br/>
<div class="mdl-grid">
  <div class="mdl-layout-spacer"></div>
  <h5>
    <br/>
    Sign
  </h5>
</div>
<hr/>
<div class="mdl-grid">
  <div class="mdl-layout-spacer"></div>
  <span style="font-size: smaller">
    Powered By LINKER IT SOLUTIONS PVT. LTD.
  </span>
</div>
<script type="text/javascript">
  $(document).ready(function () {
   window.print();
  });
</script>

app/views/students/show.html.erb
<%= link_to "<i class='material-icons'>keyboard_arrow_left</i> Back".html_safe,
            {controller: 'students', action: 'index',
             standard: @student.student_class, section: @student.division },
            class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--accent' %>
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--4-col">
    <h3><%= @student.first_name %></h3>
    <div style="overflow: auto">
      <div class="mdl-typography--text-center">
        <%= image_tag @student.profile_photo.blank? ? 'user.png' : @student.profile_photo, :width => 150, :height => 150, class: 'img-circle' %>
      </div>
      <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp" id="table_stud_profile">
        <tbody>
        <tr>
          <th>Father occupation</th>
          <td class="mdl-data-table__cell--non-numeric"><%= @student.father_occupation %></td>
        </tr>
        <tr>
          <th>Mother name</th>
          <td class="mdl-data-table__cell--non-numeric"><%= @student.mother_name %></td>
        </tr>
        <tr>
          <th>Address</th>
          <td class="mdl-data-table__cell--non-numeric"><%= @student.address %></td>
        </tr>
        <tr>
          <th>Father Mobile No.</th>
          <td class="mdl-data-table__cell--non-numeric">
            <%= @student.mobile_no %>
          </td>
        </tr>
        <tr>
          <th>College name</th>
          <td class="mdl-data-table__cell--non-numeric"><%= @student.college_name %></td>
        </tr>
        <tr>
          <th>Student class</th>
          <td class="mdl-data-table__cell--non-numeric"><%= @student.student_class %></td>
        </tr>
        <tr>
          <th>Division</th>
          <td class="mdl-data-table__cell--non-numeric"><%= @student.division %></td>
        </tr>
        <tr>
          <th>Date of birth</th>
          <td class="mdl-data-table__cell--non-numeric"><%= @student.date_of_birth %></td>
        </tr>
        <tr>
          <th>Admission date</th>
          <td class="mdl-data-table__cell--non-numeric"><%= @student.admission_date %></td>
        </tr>
        <tr>
          <th>Academic Year</th>
          <td class="mdl-data-table__cell--non-numeric"><%= if !@student.academic_year.nil?
                                                              @student.academic_year.year
                                                            else
                                                              "Academic year is not selected"
                                                            end %></td>
        </tr>
        <tr>
          <th>Actions</th>
          <td class="mdl-data-table__cell--non-numeric">
            <%= link_to 'Edit', {controller: 'students', action: 'edit', standard: @student.student_class,
                                 section: @student.division, id: @student}, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
          </td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="mdl-cell mdl-cell--8-col">
    <div class="mdl-grid">
      <div class="mdl-cell mdl-cell--3-col mdl-cell--12-col-phone">
        <h4>PAYMENT INFO.</h4>
      </div>
      <div class="mdl-cell mdl-cell--3-col mdl-cell--12-col-phone" style="padding-top: 1rem">
        <%= link_to 'Pay Fee', {controller: 'student_fees', action: 'new', student_id: @student.id}, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
      </div>
      <div class="mdl-cell mdl-cell--3-col mdl-cell--12-col-phone" style="padding-top: 1rem">
        <button id="show-transfer-dialog" type="button" class="mdl-button mdl-js-button mdl-button--raised mdl-button--accent">
          Transfer
        </button>
      </div>
      <div class="mdl-cell mdl-cell--3-col mdl-cell--12-col-phone" style="padding-top: 1rem">
        <button id="show-dialog" type="button" class="mdl-button mdl-js-button mdl-button--raised mdl-button--accent">Add Discount</button>
      </div>
    </div>

    <div class="mdl-cell mdl-cell--12-col">
      <div style="overflow: auto">
        <div>
          <h5>PREVIOUS</h5>
        </div>
        <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp" style="width: 100%">
          <thead class="students-table">
          <tr>
            <th class="mdl-data-table__cell--non-numeric">Academic Year</th>
            <th class="mdl-data-table__cell--non-numeric">Class</th>
            <th class="mdl-data-table__cell--non-numeric">Division/section</th>
            <th class="mdl-data-table__cell--non-numeric">Allocated fee</th>
            <th class="mdl-data-table__cell--non-numeric">Paid Fee</th>
            <th class="mdl-data-table__cell--non-numeric">Balance fee</th>
          </tr>
          </thead>

          <tbody>
          <% if @student.pre_student_garbages.nil? %>
              <tr>
                <td colspan="8" class="mdl-data-table__cell--non-numeric">No previous record</td>
              </tr>
          <% else %>
              <% @student.pre_student_garbages.each do |student_fee| %>
                  <tr>
                    <td class="mdl-data-table__cell--non-numeric"><%= student_fee.academic_year.year %></td>
                    <td class="mdl-data-table__cell--non-numeric"><%= student_fee.fee_structure.student_class %></td>
                    <td class="mdl-data-table__cell--non-numeric"><%= student_fee.fee_structure.section %></td>
                    <td class="mdl-data-table__cell--non-numeric">&#8377; <%= number_to_indian_currency(student_fee.allocated_fee) %></td>
                    <td class="mdl-data-table__cell--non-numeric">&#8377; <%= number_to_indian_currency(student_fee.paid_fee) %></td>
                    <td class="mdl-data-table__cell--non-numeric">&#8377; <%= number_to_indian_currency(student_fee.balance_fee) %></td>
                  </tr>
              <% end %>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>

    <div class="mdl-cell mdl-cell--12-col">
      <div style="overflow: auto">
        <div>
          <h5>CURRENT</h5>
        </div>
        <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp" style="width: 100%">
          <thead class="students-table">
          <tr>
            <th class="mdl-data-table__cell--non-numeric">Payment date</th>
            <th class="mdl-data-table__cell--non-numeric">Installment no</th>
            <th class="mdl-data-table__cell--non-numeric">Amount</th>
            <th class="mdl-data-table__cell--non-numeric">Payment method</th>
            <th class="mdl-data-table__cell--non-numeric">Payment desc</th>
            <th class="mdl-data-table__cell--non-numeric">Paid by</th>
            <th class="mdl-data-table__cell--non-numeric">Received by</th>
            <th class="mdl-data-table__cell--non-numeric">Print</th>
          </tr>
          </thead>

          <tbody>
          <% if @student.student_fees.where(academic_year_id: @student.academic_year.id).all.blank? %>
              <tr>
                <td colspan="8" class="mdl-data-table__cell--non-numeric">NOTHING TO SHOW</td>
              </tr>
          <% else %>
              <% @student.student_fees.where(academic_year_id: @student.academic_year.id).each do |student_fee| %>
                  <tr>
                    <td class="mdl-data-table__cell--non-numeric"><%= student_fee.payment_date %></td>
                    <td class="mdl-data-table__cell--non-numeric"><%= student_fee.installment_no %></td>
                    <td class="mdl-data-table__cell--non-numeric">&#8377; <%= number_to_indian_currency(student_fee.amount.to_f.round(2)) %></td>
                    <td class="mdl-data-table__cell--non-numeric"><%= student_fee.payment_method %></td>
                    <td class="mdl-data-table__cell--non-numeric"><%= student_fee.payment_desc %></td>
                    <td class="mdl-data-table__cell--non-numeric"><%= student_fee.paid_by %></td>
                    <td class="mdl-data-table__cell--non-numeric"><%= student_fee.received_by %></td>
                    <td class="mdl-data-table__cell--non-numeric">
                      <%= link_to "<i class='material-icons' id='tt_delete_#{student_fee.id}'>print</i>".html_safe, {controller: 'students', action: 'print_receipt', id: student_fee},
                                  class: 'mdl-button mdl-js-button mdl-button--icon' %>
                    </td>
                  </tr>
              <% end %>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="mdl-cell--12-col">
      <% if current_user.role == 'ADMIN' %>
          <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp" style="float: right !important;">
            <tbody>
            <tr>
              <th>Allocated Fee</th>
              <td class="mdl-data-table__cell--non-numeric">&#8377; <%= number_to_indian_currency(@student.allocated_fee.to_f.round(2)) %></td>
            </tr>
            <tr>
              <th>Discount</th>
              <td class="mdl-data-table__cell--non-numeric">&#8377; <%= number_to_indian_currency(@student.discount.to_f.round(2)) %></td>
            </tr>
            <tr>
              <th>Paid Fee</th>
              <td class="mdl-data-table__cell--non-numeric">&#8377; <%= number_to_indian_currency(@student.total_paid.to_f.round(2)) %></td>
            </tr>
            <tr>
              <th>Balance Fee</th>
              <td class="mdl-data-table__cell--non-numeric">&#8377; <%= number_to_indian_currency((previous_balance(@student) + @student.allocated_fee.to_f.round(2) - @student.discount.to_f.round(2)) - @student.total_paid.to_f.round(2)) %></td>
            </tr>
            </tbody>
          </table>
      <% end %>
    </div>
  </div>
</div>


<dialog class="mdl-dialog" id="discount-dialog">
  <h5 class="mdl-dialog__title">Enter Discount</h5>
  <form action="<%= update_discount_path %>" data-remote="true">
    <div class="mdl-dialog__content">
      <input type="hidden" name="id" value="<%= @student.id %>">
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label" id="allocated_fee_div">
        <input type="text" name="discount" id="discount" class="mdl-textfield__input" pattern="[0-9]+(\.[0-9][0-9]?)?">
        <label for="discount" class="mdl-textfield__label">Discount</label>
        <span class="mdl-textfield__error">Only decimal numbers with precision of 2 are allowed</span>
      </div>
      <div class="mdl-dialog__actions">
        <button type="submit" class="mdl-button">Save</button>
        <button type="button" class="mdl-button close">Close</button>
      </div>
    </div>
  </form>
</dialog>

<dialog class="mdl-dialog" id="transfer_student">
  <h5 class="mdl-dialog__title">Transfer</h5>
  <%= form_for(@pre_student_garbage) do |f| %>
      <% if @pre_student_garbage.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@pre_student_garbage.errors.count, "error") %> prohibited this pre_student_garbage from being saved:</h2>

            <ul>
              <% @pre_student_garbage.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <%= f.hidden_field :academic_year_id, value: @student.academic_year.id %>
      <%= f.hidden_field :student_id, value: @student.id %>
      <%= f.hidden_field :fee_structure_id, value: FeeStructure.where(student_class: @student.student_class, section: @student.division).limit(1).first.id %>
      <%= f.hidden_field :allocated_fee, value: @student.allocated_fee.to_f %>
      <%= f.hidden_field :paid_fee, value: @student.total_paid.to_f %>
      <%= f.hidden_field :balance_fee, value: ((@student.allocated_fee.to_f.round(2) - @student.discount.to_f.round(2)) - @student.total_paid.to_f.round(2))%>

      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= f.select(:new_academic_year, options_for_select(AcademicYear.where.not(id: @student.pre_student_garbages.map {|p| p.academic_year.id}).all.map { |f| [f.year, f.id] }),
                     {}, class: 'mdl-textfield__input', id: 'student_academic_year') %>
        <%= f.label :new_academic_year, class: 'mdl-textfield__label', for: 'student_academic_year' %>
      </div>

      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= f.select(:new_student_class, options_for_select(FeeStructure.all.map { |f| [f.structure, f.id] }),
                     {}, class: 'mdl-textfield__input', id: 'student_class') %>
        <%= f.label :new_student_class, class: 'mdl-textfield__label', for: 'student_class' %>
      </div>

      <div class="mdl-dialog__actions">
        <button type="submit" class="mdl-button" data-confirm="Are you sure?">Submit</button>
        <button type="button" class="mdl-button close">Close</button>
      </div>
  <% end %>
</dialog>
<script>
    var dialog = document.querySelector('#discount-dialog');
    var transferDialog = document.querySelector('#transfer_student');
    var showDialogButton = document.querySelector('#show-dialog');

    var showTransferDialogButton = document.querySelector('#show-transfer-dialog');
    if (! dialog.showModal) {
        dialogPolyfill.registerDialog(dialog);
    }


    showDialogButton.addEventListener('click', function() {
        dialog.showModal();
    });


    if (! transferDialog.showModal) {
        dialogPolyfill.registerDialog(transferDialog);
    }


    showTransferDialogButton.addEventListener('click', function() {
        transferDialog.showModal();
    });


    dialog.querySelector('.close').addEventListener('click', function() {
        dialog.close();
    });


    transferDialog.querySelector('.close').addEventListener('click', function() {
        transferDialog.close();
    });
</script>

app/views/students/update_discount.js.erb
location.reload();