config/routes.rb
Rails.application.routes.draw do
  resources :pre_student_garbages
  resources :academic_years
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :office_expenses
  resources :fee_structures
  resources :student_fees
  resources :class_infos
  resources :students
  root 'class_infos#index'

  get 'get_allocated_fee', to: 'students#update_allocated_fee'
  get 'update_discount', to: 'students#update_discount'
  get 'print_receipt', to: 'students#print_receipt'

  get 'student_dashboard', to: 'students#dashboard'
  get 'search_student_by_name', to: 'students#search_student_name'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pre_student_garbage.rb
class PreStudentGarbage < ApplicationRecord
  belongs_to :academic_year
  belongs_to :student
  belongs_to :fee_structure

  attr_accessor :new_student_class
  attr_accessor :new_academic_year
end

app/controllers/pre_student_garbages_controller.rb
class PreStudentGarbagesController < ApplicationController
  before_action :set_pre_student_garbage, only: [:show, :edit, :update, :destroy]

  # GET /pre_student_garbages
  # GET /pre_student_garbages.json
  def index
    @pre_student_garbages = PreStudentGarbage.all
  end

  # GET /pre_student_garbages/1
  # GET /pre_student_garbages/1.json
  def show
  end

  # GET /pre_student_garbages/new
  def new
    @pre_student_garbage = PreStudentGarbage.new
  end

  # GET /pre_student_garbages/1/edit
  def edit
  end

  # POST /pre_student_garbages
  # POST /pre_student_garbages.json
  def create
    @pre_student_garbage = PreStudentGarbage.new(pre_student_garbage_params)

    if !pre_student_garbage_params[:student_id].blank?
      @student = Student.find(pre_student_garbage_params[:student_id])
      @fee_structure = FeeStructure.find(pre_student_garbage_params[:new_student_class])
      if @student.academic_year.id == pre_student_garbage_params[:new_academic_year].to_i
        respond_to do |format|
          format.html { redirect_to @student, alert: 'Already in same academic year.' }
        end
      else
        if @student.update(academic_year_id: pre_student_garbage_params[:new_academic_year],
                           student_class: @fee_structure.student_class,
                           division: @fee_structure.section, allocated_fee: @fee_structure.allocated_fee,
                           discount: 0, total_paid: 0)
          respond_to do |format|
            if @pre_student_garbage.save
              format.html { redirect_to @student, notice: 'Student Successfully transferred.' }
              format.json { render :show, status: :created, location: @pre_student_garbage }
            else
              format.html { render :new }
              format.json { render json: @pre_student_garbage.errors, status: :unprocessable_entity }
            end
          end
        end
      end
    end
  end

  # PATCH/PUT /pre_student_garbages/1
  # PATCH/PUT /pre_student_garbages/1.json
  def update
    respond_to do |format|
      if @pre_student_garbage.update(pre_student_garbage_params)
        format.html { redirect_to @pre_student_garbage, notice: 'Pre student garbage was successfully updated.' }
        format.json { render :show, status: :ok, location: @pre_student_garbage }
      else
        format.html { render :edit }
        format.json { render json: @pre_student_garbage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pre_student_garbages/1
  # DELETE /pre_student_garbages/1.json
  def destroy
    @pre_student_garbage.destroy
    respond_to do |format|
      format.html { redirect_to pre_student_garbages_url, notice: 'Pre student garbage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pre_student_garbage
      @pre_student_garbage = PreStudentGarbage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pre_student_garbage_params
      params.require(:pre_student_garbage).permit(:academic_year_id, :student_id, :fee_structure_id, :allocated_fee, :paid_fee, :balance_fee, :new_student_class,
      :new_academic_year)
    end
end

app/helpers/pre_student_garbages_helper.rb
module PreStudentGarbagesHelper
end

app/views/pre_student_garbages/_form.html.erb
<%= form_for(pre_student_garbage) do |f| %>
  <% if pre_student_garbage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pre_student_garbage.errors.count, "error") %> prohibited this pre_student_garbage from being saved:</h2>

      <ul>
      <% pre_student_garbage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :academic_year_id %>
    <%= f.number_field :academic_year_id %>
  </div>

  <div class="field">
    <%= f.label :student_id %>
    <%= f.number_field :student_id %>
  </div>

  <div class="field">
    <%= f.label :fee_structure_id %>
    <%= f.number_field :fee_structure_id %>
  </div>

  <div class="field">
    <%= f.label :allocated_fee %>
    <%= f.text_field :allocated_fee %>
  </div>

  <div class="field">
    <%= f.label :paid_fee %>
    <%= f.text_field :paid_fee %>
  </div>

  <div class="field">
    <%= f.label :balance_fee %>
    <%= f.text_field :balance_fee %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pre_student_garbages/edit.html.erb
<h1>Editing Pre Student Garbage</h1>

<%= render 'form', pre_student_garbage: @pre_student_garbage %>

<%= link_to 'Show', @pre_student_garbage %> |
<%= link_to 'Back', pre_student_garbages_path %>

app/views/pre_student_garbages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pre Student Garbages</h1>

<table>
  <thead>
    <tr>
      <th>Academic year</th>
      <th>Student</th>
      <th>Fee structure</th>
      <th>Allocated fee</th>
      <th>Paid fee</th>
      <th>Balance fee</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pre_student_garbages.each do |pre_student_garbage| %>
      <tr>
        <td><%= pre_student_garbage.academic_year_id %></td>
        <td><%= pre_student_garbage.student_id %></td>
        <td><%= pre_student_garbage.fee_structure_id %></td>
        <td><%= pre_student_garbage.allocated_fee %></td>
        <td><%= pre_student_garbage.paid_fee %></td>
        <td><%= pre_student_garbage.balance_fee %></td>
        <td><%= link_to 'Show', pre_student_garbage %></td>
        <td><%= link_to 'Edit', edit_pre_student_garbage_path(pre_student_garbage) %></td>
        <td><%= link_to 'Destroy', pre_student_garbage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pre Student Garbage', new_pre_student_garbage_path %>

app/views/pre_student_garbages/new.html.erb
<h1>New Pre Student Garbage</h1>

<%= render 'form', pre_student_garbage: @pre_student_garbage %>

<%= link_to 'Back', pre_student_garbages_path %>

app/views/pre_student_garbages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Academic year:</strong>
  <%= @pre_student_garbage.academic_year_id %>
</p>

<p>
  <strong>Student:</strong>
  <%= @pre_student_garbage.student_id %>
</p>

<p>
  <strong>Fee structure:</strong>
  <%= @pre_student_garbage.fee_structure_id %>
</p>

<p>
  <strong>Allocated fee:</strong>
  <%= @pre_student_garbage.allocated_fee %>
</p>

<p>
  <strong>Paid fee:</strong>
  <%= @pre_student_garbage.paid_fee %>
</p>

<p>
  <strong>Balance fee:</strong>
  <%= @pre_student_garbage.balance_fee %>
</p>

<%= link_to 'Edit', edit_pre_student_garbage_path(@pre_student_garbage) %> |
<%= link_to 'Back', pre_student_garbages_path %>