config/routes.rb
Rails.application.routes.draw do
  resources :pre_student_garbages
  resources :academic_years
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :office_expenses
  resources :fee_structures
  resources :student_fees
  resources :class_infos
  resources :students
  root 'class_infos#index'

  get 'get_allocated_fee', to: 'students#update_allocated_fee'
  get 'update_discount', to: 'students#update_discount'
  get 'print_receipt', to: 'students#print_receipt'

  get 'student_dashboard', to: 'students#dashboard'
  get 'search_student_by_name', to: 'students#search_student_name'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/academic_year.rb
class AcademicYear < ApplicationRecord
  has_many :students
  has_many :pre_student_garbages

  def year
    "#{start_month} #{start_year} - #{end_month} #{end_year}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/class_info.rb
class ClassInfo < ApplicationRecord
end

app/models/expense_type.rb
class ExpenseType < ApplicationRecord
end

app/models/fee_structure.rb
class FeeStructure < ApplicationRecord
  has_many :pre_student_garbages

  def structure
    "#{student_class} - #{section}"
  end
end

app/models/office_expense.rb
class OfficeExpense < ApplicationRecord
end

app/models/pre_student_garbage.rb
class PreStudentGarbage < ApplicationRecord
  belongs_to :academic_year
  belongs_to :student
  belongs_to :fee_structure

  attr_accessor :new_student_class
  attr_accessor :new_academic_year
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :student_fees
  belongs_to :academic_year
  has_many :pre_student_garbages

  mount_uploader :profile_photo, StudentProfileUploader
end

app/models/student_fee.rb
class StudentFee < ApplicationRecord
  belongs_to :student
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy, :update_discount]

  # GET /students
  # GET /students.json
  def index
    if !params[:query].nil? && !params[:standard].nil? && !params[:section].nil?
      @students = Student.where("lower(first_name) LIKE lower(?) AND student_class = ? AND division = ?", "%#{params[:query]}%",
                                "#{params[:standard]}", "#{params[:section]}").order(:created_at => "DESC")
    elsif !params[:standard].nil? && !params[:section].nil?
      @students = Student.where("student_class = ? AND division = ?", "#{params[:standard]}",
                                "#{params[:section]}").order(:created_at => "DESC")
    end

    respond_to do |format|
      format.html
      format.xls
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @pre_student_garbage = PreStudentGarbage.new
  end

  # GET /students/new
  def new
    @student = Student.new
    @fee_structure = FeeStructure.all
  end

  # GET /students/1/edit
  def edit
    @fee_structure = FeeStructure.all
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end



  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.student_fees.each do |fee|
      fee.destroy
    end
    student_class = @student.student_class
    student_section = @student.division
    @student.destroy
    
    respond_to do |format|

      format.html { redirect_to controller: 'students', action: 'index',
                                standard: student_class, section: student_section,
                                notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # custom methods
  def update_allocated_fee

    s_class = params[:s_class]
    s_section = params[:s_section]

    @allocated_fee = FeeStructure.where(:student_class => s_class,
                                       :section => s_section).limit(1).first

    respond_to do |format|
      if !@allocated_fee.blank?
        format.js {}
      else
        format.js {}
      end
    end
  end

  def update_discount
    respond_to do |format|
      if params[:discount].blank?
        format.js {}
      else
        @student.update(:discount => params[:discount])
        format.js {}
      end
    end
  end

  def print_receipt
    @payment = StudentFee.find(params[:id])
  end

  def dashboard
    @fee_structures = FeeStructure.all
  end

  def search_student_name
    @students = Student.where("lower(first_name) LIKE lower(?)", "%#{params[:name]}%") unless params[:name].blank?
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:first_name, :last_name,
                                      :father_name, :father_occupation,
                                      :mother_name, :address, :mobile_no,
                                      :date_of_birth, :college_name, :student_class,
                                      :admission_date, :division, :allocated_fee,
                                      :total_paid, :no_of_installments, :discount,
                                      :alternate_mobile, :academic_year_id, :profile_photo)
    end
end

app/helpers/academic_years_helper.rb
module AcademicYearsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def number_to_indian_currency(number)
    number.to_s.gsub(/(\d+?)(?=(\d\d)+(\d)(?!\d))(\.\d+)?/, "\\1,")
  end
end

app/helpers/class_infos_helper.rb
module ClassInfosHelper
end

app/helpers/fee_structures_helper.rb
module FeeStructuresHelper
end

app/helpers/office_expenses_helper.rb
module OfficeExpensesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/student_fees_helper.rb
module StudentFeesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
  def previous_balance(student)
    pre_bal = 0.0

    student.pre_student_garbages.each do |pre|
      pre_bal += pre.balance_fee
    end

    pre_bal
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= ClassInfo.first.class_name.upcase %></title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.4/material.indigo-pink.min.css">
    <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dialog-polyfill/0.4.9/dialog-polyfill.min.css" integrity="sha256-qVjBFbunjrWQ4IikV5dkK1ziW9XKskisX1rUbCIJEhk=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dialog-polyfill/0.4.9/dialog-polyfill.min.js" integrity="sha256-Niy7AJ0dDiIklf9lFp0ZX1gZsIBa8gQ/S241Wf5vXo4=" crossorigin="anonymous"></script>
    <!--<link href="http://ylc.sreyah.xyz/assets/material_3/css/materialize.min.css" type="text/css" rel="stylesheet" media="screen,projection">-->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>

    <!-- Always shows a header, even in smaller screens. -->
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <header class="mdl-layout__header avoid-in-print">
        <div class="mdl-layout__header-row">
          <!-- Title -->
          <span class="mdl-layout-title"><%= link_to ClassInfo.first.class_name.upcase, root_path, style: 'color: white' %>  <span id="page_name"></span></span>
          <!-- Add spacer, to align navigation to the right -->
          <div class="mdl-layout-spacer"></div>
          <form action="<%= search_student_by_name_path %>">
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
              <input class="mdl-textfield__input" type="text" id="filter_by_query" name="name" value="<%= params[:name] %>" autocomplete="off">
              <label class="mdl-textfield__label" for="filter_by_query" style="color: #F7F7F7">Search</label>
            </div>
          </form>

          <!-- Right aligned menu below button -->
          <button id="demo-menu-lower-right"
                  class="mdl-button mdl-js-button mdl-button--icon">
            <i class="material-icons">more_vert</i>
          </button>

          <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
              for="demo-menu-lower-right">
            <% if user_signed_in? %>
                <li class="mdl-menu__item data-mdl-disabled"><%= current_user.username %></li>
                <li class="mdl-menu__item--full-bleed-divider"></li>
                <%= link_to '<li class="mdl-menu__item">Edit profile</li>'.html_safe, edit_user_registration_path %>
                <%= link_to '<li class="mdl-menu__item">Log out</li>'.html_safe, destroy_user_session_path, method: :delete%>
            <% else %>
                <% link_to '<li class="mdl-menu__item">Sign out</li>'.html_safe, new_user_registration_path %>
                <%= link_to'<li class="mdl-menu__item">Log in</li>'.html_safe, new_user_session_path %>
            <% end %>
          </ul>
        </div>
      </header>
      <div class="mdl-layout__drawer avoid-in-print">
        <span class="mdl-layout-title" style="padding: 0 !important;"><%= image_tag 'logo-dnyanjyoti.jpg', class: 'responsive', width: 239, height: 200 %></span>
        <nav class="mdl-navigation">
          <a class="mdl-navigation__link" href="<%= student_dashboard_path %>">Students</a>
          <a class="mdl-navigation__link" href="<%= student_fees_path %>">Fee Collection</a>
          <a class="mdl-navigation__link" href="<%= academic_years_path %>">Academic Years</a>
          <a class="mdl-navigation__link" href="<%= fee_structures_path %>">Fee Structure</a>
          <a class="mdl-navigation__link" href="<%= office_expenses_path %>">Office Expense</a>
        </nav>
      </div>
      <main class="mdl-layout__content">
        <div class="page-content">

          <!-- Your content goes here -->
          <div class="mdl-grid avoid-in-print">
            <div class="mdl-layout-spacer"></div>
            <% if notice %>
                <p class="alert alert-success"><%= notice %></p>
            <% end %>
            <% if alert %>
                <p class="alert alert-danger"><%= alert %></p>
            <% end %>
            <div class="mdl-layout-spacer"></div>
          </div>
            <%= yield %>
        </div>
      </main>
      <footer class="mdl-mini-footer avoid-in-print" style="padding-top: 5px !important; padding-bottom: 10px !important;">
        <div class="mdl-mini-footer__left-section">
          <div class="mdl-logo">&copy; <%= ClassInfo.first.class_name.upcase %></div>
        </div>
        <div class="mdl-mini-footer__right-section">
          <div class="mdl-logo">POWERED BY LINKER IT SOLUTIONS </div>
        </div>
        <script type="text/javascript">
            $("#search_student_field").on('keyup change', function () {
                get_searched_student($("#search_student_field").val());
            });
            var get_searched_student = function (student_name) {

                $.ajax({
                    url: '<%= search_student_by_name_url %>',
                    data: 'name='+ student_name,
                    type: 'GET'
                });
            };
        </script>

      </footer>
    </div>
  </body>
</html>